services:
  # image project
  api-backend :
    build:
      target: app-dev
      context: .
      args:
        APP_BASE_DIR: ${APP_BASE_DIR-.}
        COMPOSER_AUTH: "{}"
      dockerfile: Dockerfile
    platform: linux/x86_64
    restart: unless-stopped
    volumes:
      - ./docker/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ${APP_BASE_DIR-.}/Application:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment: 
      TZ: America/Sao_Paulo
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 8096M
        reservations:
          cpus: '1'
          memory: 2048M
    security_opt:
      - no-new-privileges:true
    networks:
      - net_app

  web:
    build:
      context: .
      target: web-dev
      args:
        APP_BASE_DIR: ${APP_BASE_DIR-.}
    restart: unless-stopped
    ports:
      - "9923:8080"
    volumes:
      - ${APP_BASE_DIR-.}/Application/public:/app/public
      - ${APP_BASE_DIR-.}/docker/logs/nginx:/var/log/nginx
    environment:
      TZ: America/Sao_Paulo
      PHP_FPM_HOST: api-backend
    depends_on:
      - api-backend
    networks:
      - net_app
  mysql-api-backend:
    image: mysql:latest
    container_name: mysql-api-backend
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MYSQL_ROOT_PASSWORD: "123123"
      MYSQL_DATABASE: desafio-super-backend
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "9922:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - net_app
  # jdbc:mysql://localhost:9922/desafio-super-backend?allowPublicKeyRetrieval=true&useSSL=false
  redis-api-backend:
    container_name: redis-api-backend
    image: redis:latest
    command: redis-server --maxmemory 2GB --maxmemory-policy allkeys-lru
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
        - "9924:6379"
    # volumes:
        # - "./docker/redis:/data"
    networks:
      - net_app
networks:
    net_app:
      driver: bridge